---
title: "Gov 50 Final Project"
author: "Jake Brownley"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...

campaign ad effectiveness, international aid spent by the US, crime rates in major US cities, spending of leaders in under developed countries, the economics of the 2024 MLB season, and air and sea pollution in the United States. These interests stem from my intrigue in government elections, public policies, international relations, and sports. 

```{r}
df = read.csv("air_quality_file.csv")
```

The dataset I will be using is the City of New York Air Quality Data Catalog. In interpreting this data, I will look to answer the following research question, does the population of New York City directly affect it's air quality? I hypothesize that as the population of New York City increases the quality of air decreases. As the population increases, I expect more harmful gases to be put into the atmosphere through vehicles, homes, factories, and individual citizens. The explanatory variable of interest is th quality of air at certain years. The air quality of New York City is measured by calculating the ozone, fine particles, black carbon, nitric oxide, nitrogen dioxide, and sulfur dioxide. The outcome variable of interest is the average air quality measured each year in New York City. This is measured by using the air quality measurements and cross comparing them with the population of New York City in that given year. If the air quality worsens as the population rises, then my hypothesis proves correct; however, if the air quality remains the same, or improves as the population rises, then my hypothesis proves incorrect. 